version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - echo update npm...
      - npm install -g n
      - n latest
      - npm update -g npm
      - echo node -v
      - node -v
      - echo npm -v
      - npm -v
      - echo install yarn...
      - npm install -g yarn
      - echo yarn -v
      - yarn -v

  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - yarn run build

  post_build:
    commands:
      - echo Build completed on `date`
      - echo doing nothing

artifacts:
  files:
    - '**/*'
  discard-paths: yes
