version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
        - echo Installing dependencies with Yarn...
        - yarn set version berry  # Set Yarn Berry as the Yarn version
        - yarn install  # Use Yarn Berry to install dependencies

 build:
    commands:
        - echo Build started on `date`
        - echo Compiling the Node.js code...
        - yarn build  # Use Yarn Berry to run the build script

  post_build:
    commands:
      - echo Build completed on `date`
      - echo doing nothing

artifacts:
  files:
    - '**/*'
  discard-paths: yes
